### ISSUE TITLE
Manifest description

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/registry-dev#124]
It would be nice if Metadata had a `description` field for use by Pursuit, see https://github.com/purescript/pursuit/issues/431

https://github.com/purescript/registry/blob/bfa073019247439c000feb304555675711948514/v1/Metadata.dhall#L18-L25

**Comment by f-f** [comment]
Hey @jamesdbrock! It would be indeed good to have a `description` field, but I think we should have it in the `Manifest`, rather than the `Metadata`. Here:

https://github.com/purescript/registry/blob/bfa073019247439c000feb304555675711948514/v1/Manifest.dhall#L13-L24

The difference being that the `Manifest` is totally in the hands of the package authors as it's versioned together with the package sources, while the `Metadata` resides in this repo, it's meant to be 100% handled by our CI automation (as it contains information for CI itself), and contains sensitive information (the hashes of the package tarballs), so pull requests to it will likely be forbidden.
