### ISSUE TITLE
Add packages to a package set on upload

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#156]
Similar to #154; packages uploaded to the registry should automatically be added to the latest package set, if possible. If the package can't be added to the package set then the registry should issue a warning (but not fail the package upload). Package sets will still need manual curation (ie. a breaking change at the root of a package set will eventually need manual management to update the root package and all its dependents), but this will help keep package sets up to date over time.

To accomplish this, we'll need to:

1. Add or update the registry package to the package set that's currently in the default branch of the package sets repository
2. Compile the entire package set with its compatible compiler version(s) to verify that the package works with the set
3. If successful, commit the updated package set back to the default branch of the package sets repository

**Comment by f-f** [comment]
Something that we will need to consider is "group updates": sometimes a new version breaks many packages, and the new set will work only if all of these are updated at the same time. Easily solvable by a human, hard to automate?

**Comment by thomashoneyman** [comment]
The [spec describes how package sets generation works](https://github.com/purescript/registry/blob/master/SPEC.md#93-package-sets). 

Notably, while we do add a package to the day's set automatically, we ultimately decided not to add the package to the package sets on _upload_ and instead we add the entire day's group at once every day. That's because adding the package to a running set that gets committed once per day brings in some complications:

1. The package may not work with the package set as-is, but would work if it were added to the package set with the other packages of the day (for example, when Halogen and Halogen Hooks are updated together)
2. It's a piece of state to persist, and since we're on Actions there isn't a good way to do that without relying on job outputs or on a file in this repository, both of which I'd prefer to avoid.

**Comment by thomashoneyman** [comment]
I'm going to close this because this has been implemented, but we can reopen it or open a separate issue if we want to discuss how we could go about adding packages immediately.
