### ISSUE TITLE
Consider removing targets from the manifest

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#164]
The current manifest specification includes a `targets` key:
https://github.com/purescript/registry/blob/55bce52392cab4b595ac1f542954cfceeef2d431/v1/Manifest.dhall#L22-L23

where a `Target` is defined as:

https://github.com/purescript/registry/blob/55bce52392cab4b595ac1f542954cfceeef2d431/v1/Target.dhall#L14-L20

...but it's not entirely clear to me why we need to include targets at all in a package manifest, as the registry (implicitly, at least) relies on a single target called `lib`:

https://github.com/purescript/registry/blob/3d091b10d63350e8d374612e0eabbf825394cb40/README.md#the-package-manifest

I understand the value of targets when _developing_ a package -- it's important to be able to specify things to compile (and their extra dependencies) besides `src`, like `tests`, `bench`, `examples`, and so on. For that reason it's vital that a build tool (like Spago) can support additional targets.

But I don't see why the extra targets information needs to be included in the manifest file unless the registry or package managers depending on the registry can do something with that information. If the `lib` target is all the registry cares about, then why not flatten that target into the manifest instead of checking for a `lib` target?

**Comment by thomashoneyman** [comment]
(cc: @f-f, @hdgarrood)

**Comment by f-f** [comment]
@thomashoneyman agreed 100% with your analysis!

However, I think the main usecase for which we introduced the support for multiple targets here in the manifest was to allow package authors to depend on a target different than `lib` - specifically it was to be able to depend on some other package's `test` target (IIRC you originally had this need, but I cannot find the relevant thread right now)

So we have to figure out:
- do we want to support this usecase? If not, then "depending on some other package's tests" would not be possible at all, since there would be no trace of the "test target" in the registry. A workaround for this would be to publish the tests as a separate package, but that would require author intervention or forking.
- if we want to allow this, then we need to think about how such dependencies on targets that are not `lib` should be specified.
  I.e. if package `B.test` depends on `A.test`, how do we publish this information to the registry so that if `C.test` wants to depend on `B.test` then the package manager is able to pull all the right sources in the build?

**Comment by JordanMartinez** [comment]
Here's the thread: thomashoneyman/purescript-halogen-hooks#24

**Comment by JordanMartinez** [comment]
Moreover, I believe targets would enable things like purescript/package-sets#2, and/or enable users to [run a library's examples](https://github.com/purescript-contrib/purescript-string-parsers/pull/52#issuecomment-637892884) if it was also uploaded

**Comment by f-f** [comment]
We discussed this in a call with @thomashoneyman and @JordanMartinez, and we figured that we'd like to keep the target key as it is now, mostly because the cost of adding it later would otherwise be too high: if we omit it then we need a place to specify the `dependencies` of the package, so we'd add a key for that. But if we need to add `targets` later, then this would get confusing, as there would now be two places where the dependencies are specified: under `dependencies` and under `targets.*.dependencies`.
Leaving it in as a list gives us the option of just enforcing it to only have one element, or to expand it to multiple targets later, all in a forward-compatible manner.

**Comment by thomashoneyman** [comment]
We discussed this again in the registry call in the [`#registry` channel on the PureScript chat](https://purescript.org/chat) and came to a different conclusion. Some salient points:

1. A `purs.json` file represents a single package.
2. Every package _must_ have a target named `lib`
3. At the moment, packages can have other targets as well

The contention comes from the third point: why do we support alternate targets, and how would these targets be used? The reasons to support alternate targets include:

* You could run a package's tests as part of uploading a package, if the package has a `test` target
* You could depend on a package's `test` target when implementing your own tests (for example, you could rely on the `halogen-hooks` test suite to test your own hook implementations)
* You could depend on a package's `examples` target, reusing an example in your own application

Unfortunately, other than running a package's tests, it's not at all clear how package managers would support these other workflows. These questions are unanswered:

* How do you specify a dependency on a package _at a specific target_? For example, how do I say that my package depends on `halogen-hooks` at the `test` target? There is no mechanism for this in current package managers, and it's not clear to me how it should be added.
* As [@f-f already mentioned](https://github.com/purescript/registry/issues/164#issuecomment-826883000), how do you propagate these dependencies through packages? For example, how do I say that `halogen-hooks-extra.test`  depends on `halogen-hooks.test` and the right sources and dependencies are pulled through?

There is another way to support these use cases _without_ the concept of targets, and that's by publishing multiple packages. In this workflow:

1. You create a monorepo (`halogen-hooks`) that contains multiple packages, one package per target (`halogen-hooks`, `halogen-hooks-test`). The monorepo setup allows you to manage the library and tests together, the same as before.
2. You publish the two packages to the registry as separate packages.
3. Users who want to depend on the tests can bring in the `halogen-hooks-test` package.

This does not solve the problem of wanting to run a package's test suite as part of uploading it to package sets. Perhaps there is another mechanism we can use for that (we could check for a `spago.dhall` file containing a `test` target and run that, for example).

This _does_, for me, solve the problem of wanting to depend on a package's test suite or examples. In the overwhelming majority of cases no one is going to depend on your test suite, but in the rare cases where someone _does_ want to, we make it easy to continue development in one repo but publish a `test` package that folks can depend on downstream.

Even as an imperfect solution, there's an important benefit: we eliminate the concept of targets altogether, which is a source of complexity in the registry _and_ for all clients of the registry. And if one day we do wish to add targets we can still add an optional `targets` or `extraTargets` key which is for everything _other than_ the default `lib` target that we have always required.

**Comment by thomashoneyman** [comment]
The proposal, then, is to adjust the `Manifest` to inline the `Target` type:

https://github.com/purescript/registry/blob/5f9ef3076f9d6e4310d5993c6c3df1837707c5d8/v1/Target.dhall#L14-L20

...removing the `targets` key altogether:

https://github.com/purescript/registry/blob/5f9ef3076f9d6e4310d5993c6c3df1837707c5d8/v1/Manifest.dhall#L24-L25

...to produce a manifest of this form:

```dhall
let Manifest =
      -- The name of the package
      { name : Text
      -- A short description of the package
      , description : Optional Text
      -- The SPDX code for the license under which the code is released
      , license : Text
      -- The version of this package
      , version : Text
      -- The git repo the package is published at
      , repository : ./Repo.dhall
      -- The directories containing source files for this package
      , sources : List Text
      -- The packages this package depends on
      , dependencies : Map Text Text
      }
```

For example, `halogen-hooks` would be represented by these two packages (note the different `subdir` and `dependencies` keys)

```json
{ "name": "halogen-hooks"
, "license": "MIT"
, "version": "1.0.0"
, "repository": { "githubOwner": "thomashoneyman", "githubRepo": "purescript-halogen-hooks", "subdir": "lib" }
, "sources": [ "src" ]
, "dependencies": { "halogen": ">=5.0.0 <7.0.0" }
}
```

```json
{ "name": "halogen-hooks-test"
, "license": "MIT"
, "version": "1.0.0"
, "repository": { "githubOwner": "thomashoneyman", "githubRepo": "purescript-halogen-hooks", "subdir": "test" }
, "sources": [ "src" ]
, "dependencies": { "halogen": ">=5.0.0 <7.0.0", "halogen-hooks": ">=1.0.0 <2.0.0" }
}
```

**Comment by artemisSystem** [comment]
After thinking about it more, that sounds good to me too. The complexity isn't really worth it, especially since it would probably mean that depending on a package means you also end up downloading its tests, and all its transitive dependencies' tests. A monorepo solution for publishing tests/examples is good enough if users want to depend on a package's tests/examples, and if we in the future want to allow packages to also optinally publish their test suite, so that it can be run before uploading to the package set, we could support that via an `extraTargets` key or similar.

**Comment by thomashoneyman** [comment]
One potential downside: a `purs.json` manifest could no longer be reused by other package managers to manage multiple targets, Spago-style. Instead, other package managers would have to have their own configuration format and generate a `purs.json` the same as Spago does.

Of course, we never designed `purs.json` to be both a package manager config file _and_ a package manifest, so this is probably OK. If we were going to do that then we would need to approach the `purs.json` very differently, explicitly looking to serve potential package manager needs.

**Comment by f-f** [comment]
We acutally started out like that, with the idea that `purs.json` could be the universal format used by all package managers. The reality though is that different package managers will have different needs, so one would end up with many different overlapping and and possibly opposite concerns.
We moved away from that and now this file really contains the smallest amount of information that we need to be able to allow people to use a package.
So I don't think it's really a downside, more like a natural implication of this design decision.

**Comment by JordanMartinez** [comment]
I wasn't on the call, but the conclusions sound good to me!
