### ISSUE TITLE
Clarify the mirroring story

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#21]
[During the meetup](https://discourse.purescript.org/t/small-purescript-online-meetup/1344) the other day, the topic of "aren't we over-relying on GitHub?" was brought up.

This makes sense as GitHub seems to go down regularly, so while we don't have to take any specific measures about that right now, we should at least take this into account in the design, so we can easily put in place any measures at a later time.

The main concerns we discussed are:
- how do we mirror the registry in practice? Right now there are instructions on how it's possible in principle, but maybe we should think of a more concrete plan - possible options for storage could be DigitalOcean or S3 or B2, or something else.
  Moreover, it's not clear if it would be possible to get "hooks" for new package uploads: so that if someone wants to keep a mirrored version of the storage they'd get notifications from the Curator "hey I'm uploading this package, you should mirror it".
  As a final note, this should be taken into account when integrating with package managers: how do we keep track of "alternative storage locations"? Should this be a setting of package managers or should this be saved in the registry? It's definitely a design question that is unexplored so far and should be addressed.
- how can people "mirror" package sets? I.e. one desire that was expressed was "can I just package the whole package set in a tarball and use that if Github is down?" - This is already possible today if you "install all packages in the set" and then package up your `.spago` folder and upload that somewhere.
  However, maybe we could automate this downstream - e.g. we could have Spago commands that take care of this (something like `spago set-backup` and `spago set-restore`), and/or this could be taken into account while addressing the concerns in the previous point

**Comment by hdgarrood** [comment]
RSS could be a good option for letting people know when new packages are uploaded, I think.

**Comment by f-f** [comment]
The new draft in #76 clarifies:
- how to set up new mirrors, and where these alternative storage locations are referenced
- the fact that we are likely to provide a stream that you can subscribe to get package updates (likely RSS)

The part about "mirroring package sets" is more of a transient concern that we have right now - people would be able to have company-wide registry mirrors, and install the package set from there, which I think covers this usecase pretty well.

So it seems to me that all the original concerns have been addressed by the update - I'll close this issue, but let's reopen if we figure out that we missed something

**Comment by f-f** [comment]
@hdgarrood I just realized that _Pursuit_ could be a great consumer for such RSS feed, so that people wouldn't have to upload packages, but they'd be pulled by Pursuit as they appear on the Registry...

**Comment by hdgarrood** [comment]
Oh right, yeah, that reminds me of my only issue with the pull model: generating docs can fail, and when it does, we ideally want that failure to occur as soon and as close to the package author as possible, so that they can address it and republish with as little hassle as possible. If you have the attempt to generate docs happen on some CI server instead, then at best, it's more of a pain, and at worst, the docs for that package don't get uploaded at all (and this does happen often in practice). This is why I've been trying to discourage people from running `pulp publish` in CI. I would really prefer that the publishing workflow was "you manually run `pulp version` and then `pulp publish` locally".

**Comment by f-f** [comment]
Why can generating docs fail?

**Comment by hdgarrood** [comment]
You can look at Language.PureScript.Publish.ErrorsWarnings for full a list. Lots of these (missing manifest file, couldn't parse package manifest, no license, invalid license) should become errors which are caught on registry submission rather than on docs generation, but I suspect a few of them wouldn't be caught until attempting to generate docs. I think the most likely reasons in practice would be that the CI job attempting to generate the docs fails to resolve dependencies (assuming it's doing solving), or if the provided version bounds are too relaxed and a compile error occurs as a result.

**Comment by hdgarrood** [comment]
Then again, I suppose the pull model is kind of inevitable if we want to avoid setting up our own web service for the registry, isn't it? So I guess we should just deal with it as best we can, perhaps by having a bot open issues if generating docs does fail.

**Comment by f-f** [comment]
How about adding "generating docs" to the required checks that are run before a package is considered "published"?
This would mean trying to generate docs in the package submission CI here, and in this way the author will be forced to fix the issue before the publishing is successful.

**Comment by hdgarrood** [comment]
That's a good question, I'm not sure. I was ideally hoping that the author could get an instant or at least near-instant answer to "has my package been published successfully (including Pursuit documentation)", but I guess that's not going to be possible with this architecture in the first place, regardless of what we say about whether generating docs is necessary for publishing. Therefore, I don't think it's necessarily a big problem if a package is published without docs having been successfully generated. It could be quite irritating for the author if their package's docs don't successfully build because of a problem which isn't relevant to them (eg because the registry CI is using a solver which isn't smart enough to find a plan, but the author is using a package set so they aren't even solving at all) and that leads to their package not being published even though it was otherwise okay.

Incidentally `purs publish` gets around this problem by including the install plan in the uploaded JSON. Perhaps the "please add version X of my package to the registry" JSON blob could include an install plan too, for the same reason?
