### ISSUE TITLE
Consider updating check that dependencies are self-contained

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#226]
Currently, we check that all package dependencies are part of the registry right after fetching the bowerfile:

https://github.com/purescript/registry/blob/daf1399c458b8159deb473358a707c660af2fc27/ci/src/Registry/Scripts/BowerImport.purs#L133

However, this means that package versions could be dropped from the registry later (for example, when being converted to `Manifest`s), and if all package versions for a package are dropped then the package isn't in the registry at all.

For this reason, we could end up considering a package valid because all of its dependencies are in the registry, only to later on drop one of its dependencies from the registry.

We could avoid this problem by moving the check for self-contained dependencies for packages to be the final check.

**Comment by f-f** [comment]
I think the real issue here is that we don't drop packages in "topological order": i.e. if we are handling package `X` which depends on package `Y`, we could consider it fine when processing it (as we still have `Y` in the list of packages), but if we later find that no version of `Y` make it to the final list of valid packages, then also package `X` should be dropped, as now its dependencies would not all be in the registry anymore.
We don't check for this right now, and I'm not sure how to go at this other than recursively check for all of this until we reach a fixpoint :thinking:

**Comment by thomashoneyman** [comment]
I've assigned this to @colinwahl as he and I are working on it.

**Comment by colinwahl** [comment]
I've made good progress on this on my branch package-version-graph - I am hoping to have a PR up soon.

The last task I want to accomplish is plumbing through errors for packages with unsatisfied dependencies, so that those stats can be reported along with the rest of the stats at the end of the legacy import script.
