### ISSUE TITLE
Add script to import existing Package Sets

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#271]
Spec we typed down in a planning call some time ago:
> - package sets are going to be in the registry
> - type is going to be key:value pairs of `PackageName` and `Address`
> - ..where `Address` is an enum of `Registry | Repo | Local` as defined [here](https://github.com/purescript/registry/blob/14a8fb7c6c711ae2bcee54c4753010d57af11721/v1/Address.dhall)
> - and we'll add `assert` checks to verify that
>   1. only `Registry` packages are in the record
>   2. that the key matches the package name in there
> - we'll write a little importer from the package-sets repo to the package sets location here, that will verify if all the versions in the set are contained in the registry before importing a set

**Comment by colinwahl** [comment]
I could work on this - just wanted to go over the approach I am thinking of and get some questions answered:

My high level approach would be the following:

For each release in the package sets repo, fetch the tarball and parse the `packages.json` file, which should always exist.

For each package within a package set, check that the package@version is included in the registry. If it is not, it will be dropped from the set.

After we have figured out the list of package@versions from a package set that is in the registry, we need to do a second pass to drop any packages whose dependencies were dropped in the first check.

Once we've figured out the self-contained set of package@versions that are contained in the registry, we can produce new `packages.json` & `packages.dhall` files conforming to the new format - however, there is a chance that not all packages from the original set would be included in this migrated package set, which brings up a few questions on how to handle that case. @thomashoneyman and I came up with a few options:

1. Drop any package set containing a dropped package altogether - this could avoid confusions by users trying to use an old package set but wondering why a dependency isn't found anymore
2. Migrate all package sets regardless of any dropped packages (maybe ensuring that they are not empty)
3. Run the above migration & see how many package sets / what packages within them are dropped, and decide at that point

@f-f What do you think of the general plan, and do you prefer any of the options for handling dropped packages?

**Comment by thomashoneyman** [comment]
The first option is the only way to guarantee we don't change the package sets, but I don't think we should make this guarantee. I don't think it's a worthwhile tradeoff to reduce user confusion by dropping package sets when any package is dropped, and I don't really think it does much to reduce confusion, anyway. I don't have evidence on it yet, but I think this would remove a _lot_ of historical package sets.

There are a few reasons why I don't think this is a worthwhile tradeoff. 

First, I don't see why, when moving to the new registry, I should prefer that my package set be missing altogether rather than exist but be missing packages. I can always add packages to my personal set; it's a lot worse to be forced into upgrading all my dependency versions by switching to a later set. This problem is even worse if we drop many sets -- which I think we will, under this approach -- because it increases the likelihood I see breaking changes because of my upgraded dependencies. 

Second, I don't see how a package set missing is less confusing than the package set existing, but without some packages. Either way it's a possibly unexpected and definitely wanted situation for the user. We can perhaps do better error reporting, in that we can fail right away if you try to migrate and your package set is gone, rather than waiting for you to build your project and get the "Package missing from the set" error, but I don't think this justifies the extra burden put on the user in my first point.

Third, all of this is a problem for the user only when a package they depend on is missing from the package set. It doesn't matter what packages were dropped from the set if their dependencies are all still there.

With all this in mind, if we do decide to drop any package sets because packages are missing, then I just ask that we focus on keeping as many as we can. I think our justification should be: "How likely is it that the user is going to be forced to upgrade package sets _anyway_ if they were on this set?" If it's almost guaranteed they have to move to a different set anyway (for example, it's literally empty), then we should probably drop the set so we can give them a better error. For example, we might say that we keep any non-empty package set (maximally permissive). Or we choose some keystone libraries like `prelude` and keep any set that keeps these libraries. 

I hope we can strike a balance. Please correct me if I'm missing a significant piece of context here!

**Comment by f-f** [comment]
@thomashoneyman I appreciate your reasons and the will to keep as many sets as possible to ease transitioning for users, but I simply don't think we can give two things the same name if they are not actually the same thing.

Hence, if we are talking about "importing historical package sets" here, then the logic to decide if a package set can be mirrored here is "does it contain exactly the same packages". This also simplifies the logic proposed by @colinwahl, which is good.

I don't think we have to be concerned about "migrating existing users" here: existing users will continue to use package sets from the current location possibly for a long while, so I think it's perfectly fine if here we say "look, you can use these sets only if you have very recent packages"

This operation is meant to give us a starting point to start publishing the next package sets from here, so I'd consider it a success if we can import at least one set. Any more than that is a good-to-have but not necessary at all.

**Comment by f-f** [comment]
Some notes about implementation:
- we don't have to fetch the tarball of the package-sets release, [we can access these files directly](https://raw.githubusercontent.com/purescript/package-sets/psc-0.14.5-20220203/packages.json)
- to check if versions are in the registry we can either:
  - wait until #215, as that will give us a fully populated `registry-index` that we can read from disk
  - or build a `registry-index` by running the `LegacyImport` from here

**Comment by thomashoneyman** [comment]
> I appreciate your reasons and the will to keep as many sets as possible to ease transitioning for users, but I simply don't think we can give two things the same name if they are not actually the same thing.

I disagree; I think we can do that, and that it’s preferable versus dropping the sets altogether if we want the migration path to be as smooth as possible. However, I don’t feel that strongly about it one way or another, because:

> I don't think we have to be concerned about "migrating existing users" here: existing users will continue to use package sets from the current location possibly for a long while, so I think it's perfectly fine if here we say "look, you can use these sets only if you have very recent packages"

I agree that it is likely legacy users will continue on using the legacy package sets. Forcing users to update to a modern package set if they want to use the registry feels like a departure from our general stance on the “smoothest migration path possible,” but I personally don’t mind making users do this, and I’m happy with the plan you’ve suggested.

**Comment by f-f** [comment]
Should there be a migration path for this at all? If your build is working fine on some version of a package set for the 0.14.1 compiler, is there any value in switching to using these package sets versus continuing to use the old ones?

**Comment by thomashoneyman** [comment]
No, I don't think there is any value at all. They should keep using the legacy package sets. So you're right, there really shouldn't be a migration path for this. Getting just a handful of recent sets would be enough to help us get started.

**Comment by thomashoneyman** [comment]
@f-f What do you think of writing all the new-style package sets to a top-level `package-sets` directory alongside the `metadata` directory?

**Comment by f-f** [comment]
One of the issues of the current arrangement for package-sets is that the schema is not versioned in any way, so it's not possible to change it in a backwards-incompatible way.
This has been an issue in the past: e.g. it is the reason why we are using the fake `metadata` package as a hack to keep track of the compiler version inside the set.

So this time I'd like the sets' schema to be versioned - so that if we need to do breaking changes to the schema we can do it in a smooth way - which is the reason why right now they are in `v1/sets`.

**Comment by thomashoneyman** [comment]
I see. Is there anything else in the registry repository that will be versioned like that? Does it make sense to do `package-sets/v1` rather than a top-level `v1` so that the package sets directory is obvious upon looking at the repo contents?

**Comment by f-f** [comment]
Yeah I thought about that too, but ultimately opted for the current setup because duplicating the versioning like that might imply that the schema of the package sets is disjoint from the rest of the Registry, but it's not: the `Address` we import from the sets is a `v1/Address`.

**Comment by f-f** [comment]
What would be the use case for specifically having a `package-sets` directory in the root of the repo?

**Comment by thomashoneyman** [comment]
> Yeah I thought about that too, but ultimately opted for the current setup because duplicating the versioning like that might imply that the schema of the package sets is disjoint from the rest of the Registry, but it's not

Package sets do feel like a "product of the registry" rather than being _in_ the registry proper to me. After all, they're an example of something we push from the `registry-dev` repo off to the `registry` repo. But maybe I'm just 

> the `Address` we import from the sets is a `v1/Address`.

Don't we only use the `Address` for the package sets, though? We don't use it for anything else as far as I know.

> What would be the use case for specifically having a `package-sets` directory in the root of the repo?

Just to be really obvious to someone visiting the registry repo. They don't have to click through `v1` to see what's in there, they can see the `metadata` and `package-sets` directories right up front. But I don't think this is a big deal, and I don't mind sticking things in a `v1` directory instead if that's what you want to do.

**Comment by f-f** [comment]
> Don't we only use the `Address` for the package sets, though? We don't use it for anything else as far as I know.

Oh, that's right. `Address` used to depend on `Repo`, but it doesn't anymore, so now we are free to have a separate versioning scheme for package sets, and we could have them in `package-sets/v1` :slightly_smiling_face:

**Comment by thomashoneyman** [comment]
In the registry call this morning we discussed the need to go ahead with settling on a naming scheme for the new package sets, and implementing it for legacy package sets. That's because we [discovered in #352](https://github.com/purescript/registry/pull/352#issuecomment-1041880302) that _all_ legacy package sets are dropped when migrating.

The idea would be:

* Settle on and implement a new naming scheme, as tracked in #329
* Update #352 to migrate legacy package sets by a) dropping all packages that don't work and b) applying the new naming scheme to them

**Comment by thomashoneyman** [comment]
Instead, we're going to move all package sets generation to the registry, and mirror those sets back over to the package-sets repo. This will produce several months worth of usable package sets, in sync with one another, before our release.
