### ISSUE TITLE
Proposed specification for a GitHub package registry service

### ISSUE THREAD

**Issue by paulyoung** [purescript/registry-dev#28]
I thought this was worth sharing: https://twitter.com/mattt/status/1268611341557719040

> Over the past few weeks, I’ve had the privilege to collaborate with @clarkbw and other great folks at @GitHub on a specification for a Swift package registry service.
> 
> Here's our pitch on the Swift forums: https://forums.swift.org/t/swift-package-registry-service/37219

**Comment by f-f** [comment]
Just managed to have a thorough read through that, thanks a lot @paulyoung for linking it!
My first comment is: wow, it's super interesting that we came to such a similar design independently :heart_eyes: (though the way they put it was much clearer with the whole explanation of "push" vs "pull")

I am not sure what we should do about this - I see two main differences with the approach here:
- in their proposal each Registry is supposed to bring their own auth, while we explicitly piggyback on GitHub's one. In practice I it would be the same, since GitHub is implementing their spec?
- they are specifying an HTTP server to control the registry process, while I'm trying to completely get rid of that, by using GitHub PRs as a signal mechanism for "here's a new release".

In practice I think we should move forward with the current design for now, because of timeline reasons - involving GitHub in the process might be quite heavyweight - and once we settle for something more automated than the current situation we can consider moving to something more along the lines of their spec.

**Comment by f-f** [comment]
cc @hdgarrood @thomashoneyman do you think it's worth getting in touch with the people at GitHub to discuss this?
I'm a little hesitant about it because that could be a lot of overhead and might mean rethinking this whole thing from scratch. Moreover, I'm afraid it would tie us even more to GitHub.

**Comment by hdgarrood** [comment]
I'm not sure. It is quite appealing to take an existing API specification which presumably has had smart people work quite hard on already and let GitHub implement it for us if they would offer to do that, and the API they describe does look sensible. I do agree that tying ourselves to GitHub unnecessarily is best avoided, but at the same time the existing plan ties us very closely to GitHub already anyway, right? If there's a specification that anyone could implement, that seems like it would give us more flexibility for moving away if need be? A proper HTTP API designed for use as a package registry is probably going to end up being quite a bit easier to use than us shoehorning a package registry into GitHub releases, especially if people want to write their own tools which would communicate directly with the registry. I think my main concern would be that GitHub could easily decide they don't feel like operating it any more and turn it off, especially if they're not clearly gaining anything from hosting a package registry service for what is a relatively small community, and then we'd have to scramble to implement the API ourselves.

**Comment by f-f** [comment]
@hdgarrood a few clarifications:
> I do agree that tying ourselves to GitHub unnecessarily is best avoided, but at the same time the existing plan ties us very closely to GitHub already anyway, right?

Not really: a fundamental point of the current design is "we can migrate easily", since the metadata is in a git repo and the data in a "generic blob storage"

> A proper HTTP API designed for use as a package registry is probably going to end up being quite a bit easier to use than us shoehorning a package registry into GitHub releases

It looks like this thing about "putting artifacts into GitHub releases" is probably confusing.
We're not "shoehorning" anything: GitHub releases is just a "storage backend", and we do want to support more storage backends anyway - for redundancy and ease of migrating away.
I'll replace all the mentions of "GitHub releases" with "S3" in the current proposal to clarify this.

> I think my main concern would be that GitHub could easily decide they don't feel like operating it any more and turn it off, especially if they're not clearly gaining anything from hosting a package registry service for what is a relatively small community, and then we'd have to scramble to implement the API ourselves.

Yeah, we _did_ get burned with Bower.

**Comment by clarkbw** [comment]
👋  Happy to have a call and chat w/ you all about our plans if that's useful. We have a lot going on but don't mind making some time to help out. My email is @clarkbw @github.com

**Comment by f-f** [comment]
So we had an amazing chat with @clarkbw and he was able to provide many insights on quite some things. Thank you! :heart: 

I incorporated your feedback in the [new draft for the spec](https://github.com/purescript/registry/pull/76).
Also I thiink we don't have any other actionable item in this issue, so I'll close.
