### ISSUE TITLE
Package size limit

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#287]
Should we cap the size of tarballs to some sane limit?

We do have a cap on our storage on DO, so it might make sense to limit package size so we have some leeway.

**Comment by thomashoneyman** [comment]
I'm in favor of at least a soft limit that at least flags for review rather than outright reject. The majority of PureScript packages must come in at under 500kb, surely? Perhaps 50mb, then? We could also take our largest package, 10x it, and set that as the limit.

I believe we only include files from the `targets` in the tarball, right? That already gets rid of things like example directories, but we could also reduce tarball sizes in the common case by ignoring files listed in the user's .gitignore if present, [as NPM does](https://docs.npmjs.com/cli/v8/commands/npm-publish#files-included-in-package).

**Comment by f-f** [comment]
> The majority of PureScript packages must come in at under 500kb, surely? Perhaps 50mb, then?

Right now 3k versions sum up to 50MBs, that is an average of 20KB per package. I'd say we could set a limit at 200-500KB for now, and see how that goes, we can always adjust it later.
I'd prefer that we just set a hard limit for now, I expect that we'll take a look at failing package uploads anyways in the beginning.

> I believe we only include files from the targets in the tarball, right?

We don't do anything like that currently, but I think we definitely should!

> ignoring files listed in the user's `.gitignore` if present

If we do the above I'm not sure if we should also do this, but why not?

**Comment by f-f** [comment]
Related: how about adding a `length` attribute to each version in the Metadata, to provide file size information to clients?

**Comment by thomashoneyman** [comment]
That’s great information for Pursuit!

**Comment by f-f** [comment]
Wonderful. So, action points for this issue:
- check the size of the packaged tarball and fail the pipeline if bigger than some number (let's do 200KB for now, we'll adjust once we gather info on all the packages, after the upload)
- add a `length : Natural` field (representing the size of the tarball in bytes) to `VersionMetadata` here:
https://github.com/purescript/registry/blob/f541e9f734f7c8994e47f8e9066eae93b966de49/v1/Metadata.dhall#L14
