### ISSUE TITLE
Add publishing date to Metadata?

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#304]
Along the lines of #287 I think it would be great to add some information about when a version was published in the Metadata file.
Still not sure how this would work for legacy imports, but we can probably get information about when a tag was published to GitHub.

**Comment by thomashoneyman** [comment]
We don't have access to publication dates [when retrieving tags via `listTags`](https://docs.github.com/en/rest/reference/repos#list-repository-tags), but we could potentially fetch entire repositories instead of using the API call and then list the tags using the `git` CLI. I believe we can access tag dates that way.

Another option is to add this field to the metadata file, but have it indicate the date that the tag was published _to the registry_, where legacy imports perhaps have no date set.

If we really want the information then most likely we're going to want to use the `git` CLI on the cloned repositories themselves rather than use the GitHub API and Octokit.

**Comment by f-f** [comment]
I'm worried that cloning all the repos to query them via git might be too slow.

It looks like [there's a way](https://github.community/t/is-there-an-api-to-get-a-single-tag-by-its-tag-name/126107/3) to get detailed tag info with our current method as well: the `listTags` returns objects containing a `commit.url`, and querying that URL should return full details
