### ISSUE TITLE
Package sets naming convention and mirroring

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#329]
As [mentioned in the spec](https://github.com/purescript/registry#package-sets), this repo will be the source of truth for package set.

However, we would like to support (ideally for a long time) folks using them [from the current place](https://github.com/purescript/package-sets/releases) - this is the vast majority of the ecosystem right now, and they should not be forced to migrate all at once.

So we'll need to mirror them from [their new location](https://github.com/purescript/registry/tree/master/v1/sets) to the current one.

In practice that means that:
- we can clear out most of the `package-sets` repo. The only files left there will be a `README` (explaining the situation), the `packages.json` (for psc-package users), and the `src/packages.dhall` file (for Spago users).
- for every new package set published here, we will:
  - mirror the content to these two files
  - and publish a release in `package-sets` (note: this process copies the `src/packages.dhall` into a file in the release itself. This is important because for historical reasons Spago points to this one)

### Doing the conversion

We'll need to go from a bunch of
```dhall
...
aff = Address.Registry "v5.1.2"
...
```
to
```dhall
aff = { repo = "https://github.com/purescript-contrib/purescript-aff", dependencies = [...], version = "v5.1.2" }
```

We already have the data for the `version`, we'll need to get the dependencies and the URL from the `registry-index`.

### Naming convention

Our existing naming convention for package sets comes from the compiler version and the date the set it was published.
I always found this scheme incomplete, because it does not allow us to provide info about breakage - e.g. in the same way that [LTS Haskell](https://github.com/commercialhaskell/lts-haskell#readme) does - as the name of the set does not reflect the fact that we are dropping packages from the set.

So I would like to switch to a more informative naming scheme, but:
- I'm not sure how it would look like
- I'm not sure how to best do it in a non-breaking way

**Comment by thomashoneyman** [comment]
> So I would like to switch to a more informative naming scheme

We'd not change the naming scheme for legacy package sets, right? Seems like we might as well stick to the current naming scheme there, as it's legacy anyway.

> In practice that means that:
> 
>     * we can clear out most of the `package-sets` repo. The only files left there will be a `README` (explaining the situation), the `packages.json` (for psc-package users), and the `src/packages.dhall` file (for Spago users).
> 
>     * for every new package set published here, we will:
>       
>       * mirror the content to these two files
>       * and publish a release in `package-sets` (note: this process copies the `src/packages.dhall` into a file in the release itself. This is important because for historical reasons Spago points to this one)

We could probably start doing this in a branch (other than cutting releases), right? As a way to test that this repository can push package sets in the right format to `package-sets`?

**Comment by f-f** [comment]
> We'd not change the naming scheme for legacy package sets, right? Seems like we might as well stick to the current naming scheme there, as it's legacy anyway.

Yes, for the legacy package sets that we mirror we must use the old names

> We could probably start doing this in a branch (other than cutting releases), right? As a way to test that this repository can push package sets in the right format to package-sets?

Yes, a new branch is a great idea!

**Comment by thomashoneyman** [comment]
I have created a new branch here:
https://github.com/purescript/package-sets/tree/registry

I considered what should be done by the registry CI and what should be done by the package sets CI, and I've opted to move almost all processing from the package sets repo to the registry repo. The registry repo is responsible for creating a new package set, writing it to the legacy formats, and committing those files to the package-sets repo. It is also responsible for pushing a new `psc-*` tag to the registry to trigger a release. The package sets repo retains its CI workflow that waits for a `psc-*` tag and cuts a new release when one is received. Everything else has been removed.

@f-f let me know if that sounds fine to you; it's also described in the README in that branch. @colinwahl, so long as this works for Fabrizio, you can see what the legacy `packages.dhall` file should look like when we generate it.

> (note: this process copies the src/packages.dhall into a file in the release itself. This is important because for historical reasons Spago points to this one)

I forgot to do this; I've put the `packages.dhall` file in the root of the repository, which is where it gets written in order to make a release right now. But you're saying that Spago ignores the release, and reads the file out of the `src/packages.dhall` location anyway?

**Comment by thomashoneyman** [comment]
> Our existing naming convention for package sets comes from the compiler version and the date the set it was published. I always found this scheme incomplete, because it does not allow us to provide info about breakage - e.g. in the same way that [LTS Haskell](https://github.com/commercialhaskell/lts-haskell#readme) does - as the name of the set does not reflect the fact that we are dropping packages from the set.

I am interested in a better scheme that helps reflect breaking changes in the package set. However, I think doing so only makes sense if we intend to curate package sets the way the Stackage team does, which is an extra maintenance burden. I think we should only switch up the naming scheme if we have someone willing to do the maintenance work.

> Yes, for the legacy package sets that we mirror we must use the old names.

If we have the old names, and then we switch to new names, is this going to cause any issues for package managers that expect the current format?

**Comment by f-f** [comment]
> I am interested in a better scheme that helps reflect breaking changes in the package set. However, I think doing so only makes sense if we intend to curate package sets the way the Stackage team does, which is an extra maintenance burden. I think we should only switch up the naming scheme if we have someone willing to do the maintenance work.

For what I can see the Stackage team curates packages in the same way we do: there's a Nightly package set where they just merge things, and then every once in a while they cut a release. They seem to maintain only one release branch, as we do here.
The only thing that differs is the naming scheme: they use SemVer for the releases, so every time they drop packages (a breaking change) they bump the version number.
I don't think following this scheme would add any maintenance burden, but it would be a net improvement for users.

> If we have the old names, and then we switch to new names, is this going to cause any issues for package managers that expect the current format?

`psc-package` expects a specific format. The way we could make this backwards compatible would be to publish sets with the new naming here (used by new versions of Spago) and mirror them using the old naming scheme to the `package-sets` repo (where the old Spago and `psc-package` would pick them from)

**Comment by f-f** [comment]
> I forgot to do this; I've put the `packages.dhall` file in the root of the repository, which is where it gets written in order to make a release right now. But you're saying that Spago ignores the release, and reads the file out of the `src/packages.dhall` location anyway?

Older versions of Spago use the `src/packages.dhall` location, newer versions use the one in the release, so we need both, but we don't need a `packages.dhall` file in the root, we never had one

> I have created a new branch here: https://github.com/purescript/package-sets/tree/registry

@thomashoneyman lovely! This mostly looks good, a few notes:
- does this approach mean that the CI in this repo will call the `./release.sh` script in `package-sets`? I don't see that anymore there. Calling that script is fundamental as it updates the `latest-compatible-sets` file
- as mentioned above, the `packages.dhall` file should not go in the root, but inside the `src` folder

**Comment by colinwahl** [comment]
Coming back around to continue the conversation around new package-set naming conventions.

First, perhaps we should agree on what information we'd like to present in the package set name - the initial list I can think of:

1. A identifier such as "lts". I think this is mainly to distinguish from nightly, and perhaps we don't even need it.
2. A version for the package set, like they do in [LTS Haskell](https://github.com/commercialhaskell/lts-haskell#lts-haskell-version-your-ecosystem), specifically with breaking changes (dropping a package) being a major version bump
3. The date that the package set was released? In my opinion having the version for the package set + the `purs` version is more important than a date.
4. The version of `purs` used to validate the package set (maybe just major/minor version?)

That leaves us with something like:

* `lts-12.2-2022-01-07-purs.0.14`, if we include all of that information
* `lts-12.2-purs.0.14`, if we drop the date
* `12.2-2022-01-07-purs.0.14`, if we drop the "lts"
* `12.2-purs.0.14`, if we drop the "lts" & the date

However, none of these are valid SemVer, because they don't have a patch version. I think it'd be nice if we could have the whole package set name be valid SemVer, so maybe we could consider:

`12.2.3-2022-01-07-purs.0.14` or `12.2.3-purs-0.14`

Regardless of which we go with, we need to figure out what criteria we will use to bump the major/minor/patch versions. Maybe we can hold off on that until we decide on the format and then we can discuss those. @f-f / @thomashoneyman - what do you think of the various formats?

**Comment by thomashoneyman** [comment]
> I think it'd be nice if we could have the whole package set name be valid SemVer

What is the reason to have a valid SemVer version as the package set name?

If we do want to use valid SemVer, then we probably ought to use a build identifier instead of prerelease identifiers (signified with `+`) so we'd have something like this:

`12.2.3+purs-0.14.7-2022-01-07`

> The date that the package set was released? In my opinion having the version for the package set + the purs version is more important than a date.

The package set version is the only thing that seems absolutely mandatory.

The compiler version used to build it makes sense too. Personally, I like having the date in there too, so at a glance I can tell how recent a package set is.

Is there any room to support shorthands for this format? For example, the same set can be referenced by:

* `12.2.3+2022-01-07-purs-0.14.7`
* `12.2.3+2022-01-07`
* `12.2.3`

I'm not sure how the mechanics of this works out with Dhall, but I'm envisioning perhaps distinct Dhall files that just import the main one?

> A identifier such as "lts". I think this is mainly to distinguish from nightly, and perhaps we don't even need it.

This comes down to our release schedule. If we commit to something like Stackage where we don't bump major versions for 3-6 months at a time, then we probably _do_ want a nightly. Personally I think we should only have one package set, and we could set a more rapid cadence — perhaps a monthly sweep to bump all packages to their latest major versions?

Without multiple package sets, there's no need for the prefix. It's just:

`raw.githubusercontent.com/purescript/registry/package-sets/12.2.3+2022-01-07-purs-0.14.7.dhall`

**Comment by colinwahl** [comment]
> > I think it'd be nice if we could have the whole package set name be valid SemVer
> 
> What is the reason to have a valid SemVer version as the package set name?

I guess I didn't have a great reason other than thinking we probably don't need the "lts" tag, so we _could_ make it valid SemVer. I was also thinking maybe it'd be easier to bump the version that way, but we'd still need to update dates + purs version, so it may not save much work.

> The package set version is the only thing that seems absolutely mandatory.

I agree that's probably the only thing needed to uniquely identify a package set.

> Is there any room to support shorthands for this format?

I don't know the specifics of dhall either, but this sounds like a great approach to me, assuming the package set version uniquely identifies a package set.

**Comment by f-f** [comment]
Thanks Colin for moving this forward!

A few comments:
- I don't think we need a specific identifier such as "lts" - we could say that "a package set file" is a release, and the currently "unpublished" package set file is our nightly. However, that means that nightlies are effectively rolling (in contrast with how e.g. Stackage handles them, where they are immutable as the rest of the lts sets). Our practice though has been to release often (we used to have automated releases at some point), so I don't think we'd need a nightly
- I think using SemVer for the version is nice for consistency with the other version present in all the various places in the Registry - so I'd lean towards that, but move to something else if that gives us a practical advantage
- I think having there all the info we can is a good idea - so I like where we ended up, something like `12.2.3+2022-01-07-purs-0.14.7`
- Re dhall imports: indeed we can alias sets by just importing them, e.g. the content of `12.2.2.dhall` could be `./12.2.3+2022-01-07.dhall`, and so on. What's the point of this though? If it's just to look nicer in configs we'd want to weight that against having 3x the amount of files - things might get noisy

**Comment by colinwahl** [comment]
@f-f and I just chatted about the versions and here are our final thoughts - maybe we can pick one of these and go with it?

For now I think it will be fine to not create the alias files to avoid having tons of files & also because I think the build metadata is useful when specifying a package set.

Two options for the format:

1. `2.3.202204021-purs-0.14.1`
2. `2.3.1-20220402-purs-.14.1`

Notice in (1) the extra digit at the end of the date (the date being in YYYYMMDD format) - this is to be incremented if there happen to be multiple package set releases in a single day. In option (2) that information is moved to the patch version and the date is in YYYYMMDD format.

With the following rules for how we increment the version:

* Major version is incremented on breaking changes in the package set (package is removed or a major version of an underlying package is incremented)
* Minor version is incremented when adding a package to the package set, or a minor or patch version upgrade to an underlying package
* Depending on which option we go with, the patch version is:
  (1) The current date, with the release # identifier starting at 0 and being incremented if there are subsequent package set releases on the same date
  (2) Starts at 0, and is incremented if there are subsequent package set releases on the same date.

The differences in these options are mostly aesthetic, although now that I think about it, it may be easier to bump the release # identifier in option (2). I also prefer (2) from an aesthetics perspective - I find it easier to glance and parse out the date, and the extra build # identifier is less confusing to me in the patch position.

@thomashoneyman / @f-f What do you think? I'm hoping we can pick one and go with it for now so I can finish up the legacy package set migration script.

**Comment by f-f** [comment]
I think option 2 is good to go!

Note that for SemVer-sorting reasons we should use the `+` rather than the `-` after the patch version, since that would put the additional info in the "build metadata" segment (not used in sorting) instead of a "prerelease" segment (which affects the sorting, and doesn't have the correct semantics for what we're doing here), so in the end this would look like this:
```
2.3.1+20220402-purs-0.14.1
```

**Comment by thomashoneyman** [comment]
My thought on the “simple” version is that it’s easier to say “I’d like to upgrade to the next minor package set” by incrementing the minor number, but I guess you’d end up looking at all the sets anyways to see what you can upgrade to. So I’m happy with just the single .dhall file.

👍 from me on the format, using build metadata

**Comment by thomashoneyman** [comment]
This is now documented in the spec, so I'm closing this issue.

**Comment by thomashoneyman** [comment]
The naming convention is now documented in the spec, but we haven't begun mirroring the package sets yet.
