### ISSUE TITLE
Disallow package publication/updates if modules named `Main` or `Test.Main` are included

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/registry-dev#566]
See https://github.com/i-am-the-slime/purescript-visx/issues/1, which hindered an update to Try PureScript.

`Main` is typically the name of a module one uses for their application's entry point. Similarly, `Test.Main` is usually the entry point for running tests. If a package includes a module for either of those names, it'll prevent all users who use that library from using these commonly-used module names.

Thus, I propose disallowing package publication and updates if they include such modules in their source globs.

**Comment by f-f** [comment]
This is a big issue - there's no way we can come up with a list of forbidden module names that can't be included in the set to prevent breaking people's builds.
The obvious thought arising from this is about just letting people have whatever module names they want, but namespace them by package name. This echoes of https://github.com/purescript/purescript/issues/3493, where we are converging towards that.

**Comment by thomashoneyman** [comment]
We can't come up with a comprehensive list of forbidden module names, that's true, but `Main` and `Test.Main` are fairly universal application defaults and I think it's sensible to restrict those for libraries.

**Comment by f-f** [comment]
Definitely, I agree. I just got worried about the fact that people can now squat module names at scale, since the inclusion in the package set for new packages is automated.

**Comment by thomashoneyman** [comment]
Oh, I see what you mean. Yea, that's a potential problem!

**Comment by thomashoneyman** [comment]
We have a few options for the implementation. First, we have to decide if this is a check we want to share with Spago or not.

If we don't care about sharing the check with Spago then we can simply read all the directory names in the `output` directory after compiling the package source code, and error if any of them are `Main` or `Test.Main`. This is fast, easy, and reliable, but the check cannot be shared with Spago — the output directory we scan should be only the package source, and not tests, etc. as may be present in a Spago project's output directory.

If we do care about sharing the check with Spago then we must read the package source modules prior to compilation.

The first and most reliable way to get the module name from a file is with `language-cst-parser`; we can parse just the module name, imports, and exports with `parsePartialModule`. However, it does mean that we have to read every file in the `src` directory and anything else indicated by the `files` key, and parse out the module name to test whether it is `Main` or `Test.Main`, and it means that `spago` will have to take on the `language-cst-parser` dependency.
https://github.com/natefaubion/purescript-language-cst-parser/blob/main/src/PureScript/CST.purs#L83

The second way to get the module name from a file is to write a regex that does its best to ignore comments, whitespace, etc. and parse out the `module _ where`. This is unreliable because of code like this:

```purs
-- module Main where
{-
module Main where
-}
module X 
  ( module Main
  ) where

import Data.Int as Main
```

which makes it tough to be absolutely sure you got the parsing right.

So my suggestion is that we don't share this check with Spago, and Spago can choose to implement it separately if they want. We'll include it in the API pipeline as a simple `FS.Aff.readdir` call. We will then need to go through the registry to find any packages that run afoul of this rule and remove them.

**Comment by f-f** [comment]
I think not sharing the check is a good call - the implementation would otherwise be fiddly, and in Spago we first compile the package anyways and we have access to `purs graph` to figure out if there are any modules like these. (the Registry can't use it because it's only on relatively new compilers)
We should however put the list of the forbidden modules in the `lib`.

**Comment by MonoidMusician** [comment]
Here's a comprehensive JavaScript regex to obtain a module name (the only capturing group), adapted from Nate's CST library:
```js
/^(?:\s|#![^\r\n]*|--[^\r\n]*|\{-(?:-(?!\})|[^-]+)*(?:-\}|$))*module(?:\s|--[^\r\n]*|\{-(?:-(?!\})|[^-]+)*(?:-\}|$))*(\p{Lu}[\p{L}0-9_']*(?:\.\p{Lu}[\p{L}0-9_']*)*)/u
```

You can try it out at https://regex101.com/r/KhrPbD/4 (click on "Unit tests" on the left to see what I ran it through)
