### ISSUE TITLE
Add healthchecks to server

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#648]
We don't have any server monitoring right now, so if the registry server goes down we have no idea. However, we can use healthchecks.io service to provide monitoring and alert the infrastructure team.

If we wanted to self-host on a server apart from the registry server:
* There is a [module in nixpkgs](https://github.com/NixOS/nixpkgs/blob/fef2dfa379a6fae356a589974e5266ff16b0573b/nixos/modules/services/web-apps/healthchecks.nix) for healthchecks we can set up on the server
* The [self-hosted documentation](https://healthchecks.io/docs/self_hosted) describes the [settings we can use to configure the service](https://healthchecks.io/docs/self_hosted_configuration)
* We can use the `DISCORD_CLIENT_ID` and `DISCORD_CLIENT_SECRET` to configure an integration with our Discord server and send notifications to the #infrastructure (or #registry) channels

Note: we should only do this once #641 has merged, as this will lead to conflicts in the Nix configuration.

**Comment by f-f** [comment]
I'd argue we should use their hosted version instead of self-hosting - one should not host monitoring facilities on the same resource that needs monitoring! If the whole thing (the same server, or DigitalOcean) goes down then we'll never know 🙂 

[healthchecks.io](https://healthchecks.io/) is reliable (I use it for my own personal things since many years) and free to use for quite a few checks

**Comment by thomashoneyman** [comment]
Ha, of course. I've been having the various servers used by PureScript infrastructure on my mind lately. I agree with you. We should set it up on the hosted version.
