### ISSUE TITLE
How is unpublishing possible?

### ISSUE THREAD

**Issue by neongreen** [purescript/registry-dev#72]
> * immutability: packages are largely immutable - once a version has been published then its source code is forever packaged in the tarball uploaded to our storage
>    * ..but unpublishing will be possible for some time after publishing

How is unpublishing going to be implemented? "Make a new commit removing the file" isn't a great option because the package is still available in the history. Or do you plan to rewrite the history as well?

**Comment by f-f** [comment]
I have a new revision of the design coming up where this is explicitly handled: unpublishing versions mean that we'll keep track that a package had version X unpublished, and take down the tarball from the content storage.

In practice the "adding a commit" part is not very relevant because there's no sensitive data in there (it's all metadata), the part that matters is deleting the tarball since that contains the code that we want to unpublish. Makes sense?

**Comment by neongreen** [comment]
Oh, so the registry is not going to store data! Didn't realize that. Makes sense.

**Comment by f-f** [comment]
Wonderful. I also found the separation of data/metadata is not very clearly specified right now, so I'm addressing this as well in the new draft.

I'll keep this issue open so I'll remember to note this in the upcoming PR

**Comment by f-f** [comment]
Fixed in #76
